suppressMessages(library(tidyverse)) 
suppressMessages(library(purrr)) 
suppressMessages(library(lubridate)) 
suppressMessages(library(funModeling))
suppressMessages(library(ggplot2))
suppressMessages(library(DataExplorer))
suppressMessages(library(data.table))
data <- read.csv("data.csv")
df_status(data)
plot_missing(data)
map_df(data, function(x) sum(is.na(x)))
### Exploring the Data 
par(mfrow=c(2,2))
boxplot(data$Quantity, main ="Boxplot- Qty")
boxplot(data$UnitPrice, main = "Boxplot - Unit Price")
data<- data %>% mutate(Sale_amount = Quantity * UnitPrice)
data_pos<-data %>% filter(Sale_amount>0)
data_neg <- data %>% filter (Sale_amount<=0)
data_pos <- data_pos %>% na.omit()

